change to wget, github don't like curl

diff --git a/.copr/Makefile b/.copr/Makefile
--- a/.copr/Makefile
+++ b/.copr/Makefile
@@ -2,27 +2,19 @@ rpmdev-spectool:
 	if rpm -q rpmdevtools; then echo "RPM rpmdevtools is already installed"; else echo "RPM rpmdevtools need to be installed first"; dnf install -y rpmdevtools; fi
 
 curl:
-	if rpm -q curl; then echo "RPM curl is already installed"; else echo "RPM curl need to be installed first"; dnf install -y curl; fi
+	if which wget; then echo "RPM wget is already installed"; else echo "RPM wget need to be installed first"; dnf install -y wget; fi
 
 download: rpmdev-spectool curl
 	rpmdev-spectool $(spec) | awk '$$1 ~ /^Source/ && $$2 ~ /^http/ { print $$2 }' | while read url; do \
 		file=$$(basename $$url); \
-		package=$$(echo $$file | sed 's/-[0-9].*//g'); \
-		echo "INFO  : download source  $$file"; \
-		if [ ! -e $$file ]; then \
-			echo "NOTICE: download source: $$url (MISSING)"; \
-			download=1; \
-		fi; \
-		if [ $$download -eq 1 ]; then \
-			echo "INFO  : download source: $$url to file $$file"; \
-			curl -s -o $$file $$url; \
-			r=$$?; \
-			if [ $$r -eq 0 ]; then \
-				echo "INFO  : download source: $$url (SUCCESS)"; \
-			else \
-				echo "ERROR : download source: $$url (ERROR)"; \
-				exit 1; \
-			fi; \
+		echo "INFO  : download source: $$url to file $$file"; \
+		wget -N $$url; \
+		r=$$?; \
+		if [ $$r -eq 0 ]; then \
+			echo "INFO  : download source: $$url (SUCCESS)"; \
+		else \
+			echo "ERROR : download source: $$url (ERROR)"; \
+			exit 1; \
 		fi; \
 	done
 
